<?php

namespace BackBundle\Repository;

/**
 * CastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CastRepository extends \Doctrine\ORM\EntityRepository
{
}
