<?php

namespace BackBundle\Repository;

/**
 * CompagnyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompagnyRepository extends \Doctrine\ORM\EntityRepository
{
}
