<?php

namespace BackBundle\Repository;

/**
 * MarkersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarkersRepository extends \Doctrine\ORM\EntityRepository
{
}
