<?php

namespace BackBundle\Repository;

/**
 * MovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends \Doctrine\ORM\EntityRepository

{
    public function getAll(){
        $result= $this->createQueryBuilder('e')->getQuery()->execute();
        return $result;
    }
}
