<?php

namespace BackBundle\Repository;

/**
 * SoundtracksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundtracksRepository extends \Doctrine\ORM\EntityRepository
{
}
